### ISSUE TITLE
trim_trailing_whitespace requires a whitespace at the end of each line

### ISSUE THREAD

**Issue by dpordomingo** [src-d/platform-starter#7]
It seems that `trim_trailing_whitespace` requires a `whitespace` at the end of each line, what is not expected for `hugo/content/*.md` files

With this `.editorconfig`: 
```
[*.{diff,md}]
trim_trailing_whitespace = false
```
And this file content at `hugo/content/careers.md`
```
---
type: careers
classes: ["static"]
section: careers
url: careers
title: Job opportunitiesa
description: Our Job Opportunities. Exceptional missions require exceptional people
headerImageName: dennis-ritchie
contactemail: talent@sourced.tech
---

```
I got this error:
```
$ git commit hugo/content/careers.md -m wip
hugo/content/careers.md failed trim_trailing_whitespace on line 0: found setting 'true', should be 'false'
There are misformatted files, please fix them. Remember you can do
this by just using the following command:

        editorconfig-tools fix path/to/my/files/**/*

Aborting commit.
```

**Comment by erizocosmico** [comment]
The error message says there are misformatted files, it does not fix them. You have to remove the trailing whitespaces.

**Comment by dpordomingo** [comment]
In the example I pasted in the description of the issue, there is no "trailing whitespaces"
Even more: 
the `.editorconfig` rule for `.md` files is:
```trim_trailing_whitespace = false```
so whitespaces should be allowed
The problem is that whitespaces not allowed: they're **required**: if you add a whitespace at the end of everyline, the `pre-commit` succeed, what is not what we pretended to obtain with this rule
